### PR TITLE
Created a gitignore

### PR DESCRIPTION
**Pull request by doctor3w**
Ignores pods and regular Xcode stuff.

### CODE REVIEW

**Comment by doctor3w** [comment]
Hmm is it okay that this seems to include Natasha's commits? I thought I tried to get rid of those and just add it to the current master branch.

**Comment by anniexcheng** [comment]
@drewsdunne hmm are you branching off of master? because you seem to be taking in Natasha's commits on her natasha/models branch off master

**Comment by doctor3w** [comment]
@acheng96 I thought I was. I checked out master, reset to the head of master and then did a new checkout.

**Comment by acheng96** [comment]
@drewsdunne this should be fine given that Natasha wants you to integrate your stuff with her Swift 3 changes

**Pull request closed without merging**
